### PR TITLE
fix joystick and keyboard input localization

### LINKED ISSUE #626: Gamepad translations
How can I translate the labels inside Gamepad  configuration menu (pad directionals, stick directionals, and side buttons)?
I totally forgot this when I was checking the translation...

### PR DESCRIPTION
**Pull request by allancoding**
Should re fix #626

### CODE REVIEW

**Comment by allancoding** [comment]
When I merge from now on I will squash the commits.

File: data/emulator.js [hunk 1]
```diff
@@ -452,7 +452,10 @@ class EmulatorJS {
         this.elements.parent.appendChild(this.textElem);
     }
     localization(text, log) {
-        if (!isNaN(text)) return text;
+        if (!text) return text;
+        text = text.toString();
```
Comment (ethanaobrien) [inline data/emulator.js:457]: Why are we `toString`ing this?

File: data/emulator.js [hunk 2]
```diff
@@ -452,7 +452,10 @@ class EmulatorJS {
...
+        if (text === " ") text = "space";
```
Comment (ethanaobrien) [inline data/emulator.js]: what does this do?

File: data/emulator.js [hunk 3]
```diff
@@ -452,7 +452,10 @@ class EmulatorJS {
...
+        if (text === "") return text;
```
Comment (ethanaobrien) [inline data/emulator.js]: Will be caught by `!text`

File: data/emulator.js [hunk 4]
```diff
@@ -2245,18 +2248,20 @@ class EmulatorJS {
                     textBox2.value = "";
                     textBox1.value = "";
                     if (this.controls[i][k] && this.controls[i][k].value !== undefined) {
-                        textBox2.value = this.controls[i][k].value;
+                        textBox2.value = this.localization(String(this.controls[i][k].value));
                     }
-                    if (this.controls[i][k] && this.controls[i][k].value2 !== undefined) {
-                        textBox1.value = this.controls[i][k].value2;
+                    if (this.controls[i][k] && this.controls[i][k].value2 !== undefined && this.controls[i][k].value2 !== "") {
+                        let value2 = String(this.controls[i][k].value2).split(":");
```
Comment (ethanaobrien) [inline data/emulator.js]: Can we call the tostring function instead of using the String constructor

File: data/localization/Translate.html [hunk 5]
```diff
@@ -193,54 +203,148 @@ <h1>Translate Languages</h1>
             "R STICK UP": "-R STICK UP",
             "R STICK DOWN": "-R STICK DOWN",
             "R STICK LEFT": "-R STICK LEFT",
+<<<<<<< HEAD
```
Comment (ethanaobrien) [inline data/localization/Translate.html]: merge conflicts

File: data/localization/af-FR.json [hunk 6]
```diff
@@ -134,6 +144,23 @@
     "STICK DOWN": "COLLER",
     "STICK LEFT": "BÂTON GAUCHE",
     "STICK RIGHT": "COLLEZ À DROITE",
+<<<<<<< HEAD
```
Comment (ethanaobrien) [inline data/localization/af-FR.json]: Merge conflicts

File: data/localization/ar-AR.json [hunk 7]
```diff
@@ -128,12 +138,33 @@
     "X": "X",
     "Y": "ص",
     "L": "إل",
+<<<<<<< HEAD
```
Comment (ethanaobrien) [inline data/localization/ar-AR.json]: Im assuming every file downwards has merge conflicts

File: data/emulator.js [hunk 8]
```diff
@@ -2573,188 +2578,188 @@ class EmulatorJS {
...
-                {"type":"button","text":"Select","id":"select","location":"center","left":-5,"fontSize":15,"block":true,"input_value":2}
+                {"type":"button","text":this.localization("Start"),"id":"start","location":"center","left":60,"fontSize":15,"block":true,"input_value":3},
+                {"type":"button","text":this.localization("Select"),"id":"select","location":"center","left":-5,"fontSize":15,"block":true,"input_value":2}
             ];
             info.push(...speedControlButtons);
         } else if ('nes' === this.getControlScheme()) {
             info = [
-                {"type":"button","text":"B","id":"b","location":"right","right":75,"top":70,"bold":true,"input_value":0},
-                {"type":"button","text":"A","id":"a","location":"right","right":5,"top":70,"bold":true,"input_value":8},
+                {"type":"button","text":this.localization("B"),"id":"b","location":"right","right":75,"top":70,"bold":true,"input_value":0},
```
Comment (ethanaobrien) [inline data/emulator.js]: This is a little messy, can we remove any calls to localization within these if statements and just cycle through the info object and set these afterwards

**Review by ethanaobrien — CHANGES_REQUESTED** [review]

File: data/emulator.js (hunk 1 above)
Comment (allancoding) [reply data/emulator.js:457]: To convert it to a string if it is a number

Comment (ethanaobrien) [reply data/emulator.js:457]: Then this should be before `if (!text)` since `if (!0)` will return true

File: data/emulator.js (hunk 2 above)
Comment (allancoding) [reply data/emulator.js]: if it equals a space it changes the text to space, it is for the control mapping.

File: data/emulator.js (hunk 3 above)
Comment (allancoding) [reply data/emulator.js]: Your right that can be removed.

File: data/emulator.js (hunk 2 above)
Comment (ethanaobrien) [reply data/emulator.js]: but what does it do overall, how does it affect the outcome?

File: data/emulator.js (hunk 4 above)
Comment (allancoding) [reply data/emulator.js]: Yes

File: data/emulator.js (hunk 8 above)
Comment (allancoding) [reply data/emulator.js]: Yes lol that's a good idea, don't know why I did not think of that.

File: data/localization/Translate.html (hunk 5 above)
Comment (allancoding) [reply data/localization/Translate.html]: I will fix all of those

File: data/emulator.js (hunk 2 above)
Comment (allancoding) [reply data/emulator.js]: Because if you map the space bar then it will show a space not the actual space text.

File: data/emulator.js (hunk 1 above)
Comment (allancoding) [reply data/emulator.js:457]: I don't actually think it is necessary, I will just remove it.

File: data/emulator.js (hunk 2 above)
Comment (ethanaobrien) [reply data/emulator.js]: Oh, can we change this in the keychange event then? We shouldnt do this here

File: data/emulator.js (hunk 1 above)
Comment (ethanaobrien) [reply data/emulator.js:457]: Keep the check just in case

Comment (allancoding) [reply data/emulator.js:457]: Ok so it is good as is.

File: data/emulator.js (hunk 2 above)
Comment (allancoding) [reply data/emulator.js]: Ok I'll try

File: data/emulator.js (hunk 1 above)
Comment (ethanaobrien) [reply data/emulator.js:457]: (do `text = text.toString` first, and make sure `typeof text !== "undefined"`)

File: data/localization/ar-AR.json (hunk 7 above)
Comment (allancoding) [reply data/localization/ar-AR.json]: I think I fixed them all.

File: data/emulator.js (hunk 8 above)
Comment (allancoding) [reply data/emulator.js]: lol I forgot this

**Comment by allancoding** [comment]
That look good now?

File: data/emulator.js [hunk 9]
```diff
@@ -452,16 +452,18 @@ class EmulatorJS {
...
     localization(text, log) {
-        if (!isNaN(text)) return text;
-        if (text.includes("EmulatorJS v")) return text;
-        if (this.config.langJson) {
-            if (typeof log === "undefined") log = true;
-            if (!this.config.langJson[text] && log) {
-                if(!window.EJS_missingLang) window.EJS_missingLang = [];
-                window.EJS_missingLang.push(text);
-                console.log("Translation not found for '"+text+"'. Language set to '"+this.config.language+"'");
+        if (typeof text !== "undefined"){
```
Comment (ethanaobrien) [inline data/emulator.js]: instead of making this a big if statement, can we reverse this check

```
if (typeof text === "undefined") return;
```

File: data/emulator.js [hunk 10]
```diff
@@ -452,16 +452,18 @@ class EmulatorJS {
...
+            text = text.toString();
+            if (text.includes("EmulatorJS v")) return text;
+            if (this.config.langJson) {
+                if (typeof log === "undefined") log = true;
+                if (!this.config.langJson[text] && log) {
+                    if(!window.EJS_missingLang) window.EJS_missingLang = [];
```
Comment (ethanaobrien) [inline data/emulator.js]: (there should be a space after the if and before the `(`)

Can we define these within the emulatorjs instance?
`this.missingLanguages = []`. This should be initialized within the constructor

File: data/emulator.js [hunk 11]
```diff
@@ -452,16 +452,18 @@ class EmulatorJS {
...
+                    window.EJS_missingLang.push(text);
```
Comment (ethanaobrien) [inline data/emulator.js]:
```
if (!EJS_missingLang.includes(text)) EJS_missingLang.push(text);
```

File: data/emulator.js [hunk 12]
```diff
@@ -2245,18 +2247,24 @@ class EmulatorJS {
...
+                    if (this.controls[i][k] && this.controls[i][k].value2 !== undefined && this.controls[i][k].value2 !== "") {
+                        let value2 = this.controls[i][k].value2.toString().split(":");
+                        textBox1.value = this.localization(value2[0]) + ":" + this.localization(value2[1]);
                     }
                 })
                 
                 if (this.controls[i][k] && this.controls[i][k].value) {
-                    textBox2.value = this.controls[i][k].value;
+                    let value = this.controls[i][k].value.toString();
+                        if (value === " ") value = "space";
```
Comment (ethanaobrien) [inline data/emulator.js]: indentation error

**Review by ethanaobrien — CHANGES_REQUESTED** [review]

File: data/emulator.js [hunk 13]
```diff
@@ -452,18 +452,16 @@ class EmulatorJS {
...
-                    console.log("Translation not found for '"+text+"'. Language set to '"+this.config.language+"'");
-                }
-                return this.config.langJson[text] || text;
+        if (typeof text === "undefined") return;
+        text = text.toString();
+        if (text.includes("EmulatorJS v")) return text;
+        if (this.config.langJson) {
+            if (typeof log === "undefined") log = true;
+            if (!this.config.langJson[text] && log) {
+                if (!EJS_missingLang.includes(text)) EJS_missingLang.push(text);
```
Comment (ethanaobrien) [inline data/emulator.js]: Where is EJS_missingLang defined

**Review by ethanaobrien — CHANGES_REQUESTED** [review]

File: data/emulator.js (hunk 13 above)
Comment (allancoding) [reply data/emulator.js]: Where should I define it?

Comment (ethanaobrien) [reply data/emulator.js]: On the `this` object within the constructor. Maybe only name it `missingLang`

Comment (allancoding) [reply data/emulator.js]: like that?

Comment (ethanaobrien) [reply data/emulator.js]: yep, that's good

File: data/emulator.js [hunk 14]
```diff
@@ -2520,9 +2527,9 @@ class EmulatorJS {
         this.elements.parent.appendChild(this.virtualGamepad);
 
         const speedControlButtons = [
-            {"type":"button","text":"Fast","id":"speed-fast","location":"center","left":-35,"top":50,"fontSize":15,"block":true,"input_value":27},
-            {"type":"button","text":"Slow","id":"speed-slow","location":"center","left":95,"top":50,"fontSize":15,"block":true,"input_value":29},
-        ];
+            {"type":"button","text":this.localization("Fast"),"id":"speed-fast","location":"center","left":-35,"top":50,"fontSize":15,"block":true,"input_value":27},
+            {"type":"button","text":this.localization("Slow"),"id":"speed-slow","location":"center","left":95,"top":50,"fontSize":15,"block":true,"input_value":29},
+        ];
```
Comment (ethanaobrien) [inline data/emulator.js]: Can you remove these extra spaces, and didn't we move to where the localization is set afterwards?

**Review by ethanaobrien — CHANGES_REQUESTED** [review]

**Comment by zmarteline** [comment]
Ok, we are almost there...
Some issues:
1- buttons and direcionals translations are followed by the word undefined;

2- the  stickers, use the number 1 or -1 from the label,  could that label be ommited so it just appears X and -X? Otherwise we will get as result in the label the sticker information plus the label for regular button 1.

3- keyboard translations are not working.
fails

**Comment by ethanaobrien** [comment]
@allancoding Make sure localization never returns undefined. If it tries to return undefined it should return the original

File: data/emulator.js [hunk 15]
```diff
@@ -2245,18 +2246,24 @@ class EmulatorJS {
...
                     if (this.controls[i][k] && this.controls[i][k].value !== undefined) {
-                        textBox2.value = this.controls[i][k].value;
+                        let value = this.controls[i][k].value.toString();
+                        if (value === " ") value = "space";
+                        textBox2.value = value;
                     }
-                    if (this.controls[i][k] && this.controls[i][k].value2 !== undefined) {
-                        textBox1.value = this.controls[i][k].value2;
+                    if (this.controls[i][k] && this.controls[i][k].value2 !== undefined && this.controls[i][k].value2 !== "") {
+                        let value2 = this.controls[i][k].value2.toString().split(":");
```
Comment (ethanaobrien) [inline data/emulator.js:2254]: This broke it. It **should not** be assumed that the value has a colon. This is only on axis

File: data/emulator.js [hunk 16]
```diff
@@ -2245,18 +2246,24 @@ class EmulatorJS {
...
                 if (this.controls[i][k] && this.controls[i][k].value) {
-                    textBox2.value = this.controls[i][k].value;
+                    let value = this.controls[i][k].value.toString();
+                    if (value === " ") value = "space";
+                    textBox2.value = value;
                 }
                 if (this.controls[i][k] && this.controls[i][k].value2) {
-                    textBox1.value = "button " + this.controls[i][k].value2;
+                    let value2 = this.controls[i][k].value2.toString().split(":");
+                    textBox1.value = this.localization("button") + " " + this.localization(value2[0]) + ":" + this.localization(value2[1]);
```
Comment (ethanaobrien) [inline data/emulator.js:2266]: here too

File: data/emulator.js (hunk 15 above)
Comment (allancoding) [reply data/emulator.js:2254]: I will have it check if a : exists

**Comment by zmarteline** [comment]
Let me know when you need me to test again.

**Comment by allancoding** [comment]
@zmarteline I made my changes in #635

**Comment by zmarteline** [comment]
There is no changes regarding labels...
